### ISSUE TITLE
Уточнение документации по WebHook

### ISSUE THREAD

**Issue by Regela** [green-api/docs#11]
Здравствуйте! Не могли бы вы уточнить, по поводу WebHook. В какие именно интервалы сервер пробует доставить сообщение? Для чего есть возможность указать несколько вебхуков? Сервер будет выбирать один из них или отправлять на все? Если один из них, то по какому принципу?

**Comment by Regela** [comment]
Так-же, в доккументации не указано, что запрос будет приходить методом POST. Я очень долго ждал запрос в GET

**Comment by andrew-shamin** [comment]
Добрый день!
Вебхуки доставляются сразу же, при получении от сервера воцап.
Если ваш URL недоступен, то будут выполнятся попытки доставки с интервалом 60 сек в течение 24 часов.

Документацию дополним. Спасибо!

**Comment by Regela** [comment]
Спасибо за ответ! Правда не раскрыли тему с несколькими вебхуками. В интерфейсе есть намек что их может быть несколько, но информации о том как работает система когда их несколько я не нашел. Можете разъеснить?

**Comment by andrew-shamin** [comment]
В системе есть несколько видов вебхуков - о входящем сообщении, о статусе сообщения и пр.
Каждый вид вебкука можно включить или отключить по отдельности.
Подробнее тут https://green-api.com/docs/api/account/SetSettings/

**Comment by Regela** [comment]
![image](https://user-images.githubusercontent.com/21152498/172259604-2e05fd4f-6aad-497d-8c37-a61324048940.png)
Вот тут написано Webhook Url (URLs). Я зацепился глазом именно за это (URLs). Перечитал описание по ссылке выше, там тоже нет информации, зачем сюда можно передать несколько ссылок. Можете разъеснить этот момент? =)

**Comment by ripreal** [comment]
Поправлено
