### ISSUE TITLE
Отправка сообщения на неавторизованный аккаунт

### ISSUE THREAD

**Issue by eugene-borovov** [green-api/docs#13]
В [документации](https://green-api.com/docs/api/sending/SendMessage/) написано, что при отправке сообщения возвращаются стандартные ошибки. Но при попытке отправить сообщение на неавторизованный аккаунт, получаю успешный ответ с идентификатором сообщения. Это ошибка API или какой-то нюанс неотражённый в документации?

**Comment by ripreal** [comment]
Документация немного устарела по этоу моменту. Теперь отправка сообщений не требует авторизации. Сообщения скапливаются в очереди на 24 часа и будут отправлены при авторизации.

**Comment by eugene-borovov** [comment]
Спасибо, ценное замечание.
