### ISSUE TITLE
Вместо сообщения отображается "Ожидание сообщения. Это может занять некоторое время"

### ISSUE THREAD

**Issue by andrew-shamin** [green-api/docs#14]
**Ошибка**
В некоторых случаях при отправке сообщения методом SendMessage сообщение не доставляется до получателя. Вместо сообщения на телефоне получателя отображается _"Ожидание сообщения. Это может занять некоторое время"_.

**Уровень**
API

**Обходное решение**
1. Попросить получателя отправить ответное сообщение и повторить попытку отправки
2. Добавить получателя в контакты на телефоне и повторить отправку
3. Разлогинить и залогинить инстанс по новой (сканировать QR-код)

![Screenshot_13](https://user-images.githubusercontent.com/52354331/176668259-633d9f31-723b-408e-a5e9-601e61d63dd7.png)

**Comment by vgrishin** [comment]
_> 3. Разлогинить и залогинить инстанс по новой (сканировать QR-код)_

Это решает проблему у конкретного инстанса и там она не возникает больше?
Или это просто способ переотправки ожидающих на текущий момент сообщений?

**Comment by ripreal** [comment]
Это может решить проблему у конкретного инстанса.

**Comment by ripreal** [comment]
Исправлено, ожидайте в ближайшем обновлении

**Comment by ripreal** [comment]
Опубликовано в продакшене. Для того, чтобы заработало требуется перелогин телефона
