### ISSUE TITLE
Получение цитируемых сообщений

### ISSUE THREAD

**Issue by eugene-borovov** [green-api/docs#18]
Во всех методах отправки сообщений есть возможность указать цитируемое сообщение. Однако при получении можно получить только текстовое сообщение с цитатой, а сообщения с файлами приходят без цитаты. 

Это ограничение API?

**Comment by ripreal** [comment]
Такая функциональность пока нереализована, но будет исправлена в будущих релизах сервиса

**Comment by ripreal** [comment]
Сделано, ожидайте в ближашем обновлении

**Comment by Slikman1** [comment]
Готово, выйдет в релизе.
