### ISSUE TITLE
Требуется изменить метод GetContacts для одного номера.

### ISSUE THREAD

**Issue by Smol2022** [green-api/docs#20]
Требуется изменить метод GetContacts, чтобы можно было получать данные только по одному номеру.

**Comment by ripreal** [comment]
Сейчас получаются все контакты, номера, привязанного к ватсаппу. Если привязать другой номер, то контакты обновляются. Но есть нюансы - в список контактов также попадают групповые чаты, а также когда-то добавленные контакты, которых может быть уже нет в адресной книге привязанного номера 

Уточните, что именно требуется изменить?

**Comment by Slikman1** [comment]
Добавлен метод getContactInfo
