### ISSUE TITLE
Ошибка в наименовании файла при отправке через внешнюю обработку 1с

### ISSUE THREAD

**Issue by Smol2022** [green-api/docs#21]
**Ошибка**
Ошибка в наименовании файла при отправке через внешнюю обработку 1с: название меняется на неизвестные символы. При тестировании в Postman данной ошибки не выявлено.

**Уровень**
API

**Обходное решение**

**Comment by ripreal** [comment]
Исправлена внешняя обработка 1С. См версию 0.0.30

https://github.com/green-api/whatsapp-1c-example/releases/tag/1.0
