### ISSUE TITLE
Наблюдаются потери входящих сообщений

### ISSUE THREAD

**Issue by Smol2022** [green-api/docs#33]
**Ошибка**
В некоторых случаях наблюдаются потери входящих сообщений.

**Уровень**
API

**Обходное решение**
Нет

**Comment by Slikman1** [comment]
Случаи, когда входящее сообщение инициируется ссылкой типа https://wa.me/7xxxxxxxxxxx?text=Скидка

**Comment by Slikman1** [comment]
Потери такого типа сообщений обусловлены ошибкой на стороне вотсапа при отправке на все дополнительные устройства, кроме телефона. Например, такую ошибку возможно поймать в десктоп или веб версии, когда входящее сообщение приходит впервые, отправлено из любого устройства, кроме айфона. При получении таких сообщений, отправленных из айфонов данная проблема не наблюдается. 
Мы провели много работ для устранения таких проблем и добились потерь по сравнению с десктоп версией ниже на 80%. 
А для того, что бы пользователи всегда видели, что им пришло сообщение, но его не возможно отобразить - ввели дополнительный текстовый маркер {{SWE001}}.
