### ISSUE TITLE
Поле filename для изображения заполнилось из поля title

### ISSUE THREAD

**Issue by Smol2022** [green-api/docs#36]
**Ошибка**
Изображение пришло как документ. Поле filename заполнилось из поля title.

**Уровень**
API

**Обходное решение**
Нет

**Comment by Slikman1** [comment]
Исправлено.

**Comment by Air77777** [comment]
тоже самое для pdf файлов, пожалуйста исправьте

**Comment by Slikman1** [comment]
Ожидайте выхода релиза
https://green-api.com/docs/release/
