### ISSUE TITLE
Отсутствует ссылка на файл во входящем сообщении.

### ISSUE THREAD

**Issue by Smol2022** [green-api/docs#43]
**Ошибка**
Отсутствует ссылка на файл во входящем сообщении.

**Уровень**
API

**Обходное решение**
Нет

**Comment by Slikman1** [comment]
Ошибка возникает в тех случаях, когда приходит файл размером более 100 МБайт. Для таких файлов пока сделали маркер {{SWE002}}. Означает, что получен файл слишком большого размера.
