### ISSUE TITLE
Не приходят уведомления об исходящих фотографиях, файлах, аудио и т. д.

### ISSUE THREAD

**Issue by MrPeso4ko** [green-api/docs#7]
Не отображаются в журнале отправленных сообщений сообщения отправленные с телефона, на котором запущен инстанс. Также не приходят уведомления о таких сообщениях.

**Comment by andrew-shamin** [comment]
Включите настройку для получения вебхуков вида outgoingMessageReceived.
Настройку можно включить в личном кабинете, либо методом SetSettings, параметр outgoingMessageWebhook.

**Comment by MrPeso4ko** [comment]
Эта настройка включена, уведомления об исходящих текстовых сообщениях приходят сразу.8 июл. 2021 г. 07:50 пользователь Andrew Shamin ***@***.***> написал:

Включите настройку для получения вебхуков вида outgoingMessageReceived.

Настройку можно включить в личном кабинете, либо методом SetSettings, параметр outgoingMessageWebhook.

**Comment by andrew-shamin** [comment]
Тогда в чем вопрос? уточните, пожалуйста.

**Comment by MrPeso4ko** [comment]
Приходят уведомления об исходящих текстовых сообщениях, а об исходящих сообщениях с фото, видео, аудио и документами уведомления не приходят9 июл. 2021 г. 10:52 пользователь Andrew Shamin ***@***.***> написал:

Тогда в чем вопрос? уточните, пожалуйста.

**Comment by ripreal** [comment]
Проблема потеряла актуальность в связи с переходом на Multidevice.
