### ISSUE TITLE
Long sending of a message to groups by the sendFileByUrl method

### ISSUE THREAD

**Issue by Smol2022** [green-api/docs#81]
Long sending of a message to groups by the sendFileByUrl method

**Comment by adidesai9009** [comment]
After sending messages by sendFileByUrl method to multiple groups it goes to queue and remain in the queue for couple of minutes . It took around 3 and half hours to send 108 messages from the queue even i have set delay time as 0 milliseconds .As company claims that it send 120 message per minute which is false. The actual speed is 5-7 message per minute.  I request to developer team to process the messages in queue fast without waiting time. And one for thing when i run a loop for 108 in which i call your api request it take around 10-11 minutes to complete the loop which is so time consuming and resources consuming.I will provide some screen shots below.
<img width="1440" alt="Screenshot 2022-10-29 at 8 36 54 PM" src="https://user-images.githubusercontent.com/94288784/199223997-23865e21-6ccc-4c39-9c58-e09098659369.png">

**Comment by Smol2022** [comment]
01.11.2022, 14:36, "Aditya Desai" ***@***.***>: After sending messages by sendFileByUrl method to multiple groups it goes to queue and remain in the queue for couple of minutes . It took around 3 and half hours to send 108 messages from the queue even i have set delay time as 0 milliseconds .As company claims that it send 120 message per minute which is false. The actual speed is 5-7 message per minute. I request to developer team to process the messages in queue fast without waiting time. And one for thing when i run a loop for 108 in which i call your api request it take around 10-11 minutes to complete the loop which is so time consuming and resources consuming.I will provide some screen shots below.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>  -- С уважением, Смольянова Елена.Yours faithfully, Smolianova Elena.Компания: "GREEN API"e-mail: ***@***.***: https://green-api.com/tel.: +79065930340https://wa.me/79065930340

**Comment by adidesai9009** [comment]
> After sending messages by sendFileByUrl method to multiple groups it goes to queue and remain in the queue for couple of minutes . It took around 3 and half hours to send 108 messages from the queue even i have set delay time as 0 milliseconds .As company claims that it send 120 message per minute which is false. The actual speed is 5-7 message per minute. I request to developer team to process the messages in queue fast without waiting time. And one for thing when i run a loop for 108 in which i call your api request it take around 10-11 minutes to complete the loop which is so time consuming and resources consuming.I will provide some screen shots below. <img alt="Screenshot 2022-10-29 at 8 36 54 PM" width="1440" src="https://user-images.githubusercontent.com/94288784/199223997-23865e21-6ccc-4c39-9c58-e09098659369.png">

Hello ,
A few minutes ago i was trying Green Api send send message and i notices that regular text messages doesn’t takes time to sent but Attachment messages like Images,Videos, file takes time to send. Even while calling text message api it takes less time(1 sec) compare to calling file/Image/Video message (6-7 secs). I request developer team to process Image/Video/ files sending fast

**Comment by adidesai9009** [comment]
> After sending messages by sendFileByUrl method to multiple groups it goes to queue and remain in the queue for couple of minutes . It took around 3 and half hours to send 108 messages from the queue even i have set delay time as 0 milliseconds .As company claims that it send 120 message per minute which is false. The actual speed is 5-7 message per minute. I request to developer team to process the messages in queue fast without waiting time. And one for thing when i run a loop for 108 in which i call your api request it take around 10-11 minutes to complete the loop which is so time consuming and resources consuming.I will provide some screen shots below. <img alt="Screenshot 2022-10-29 at 8 36 54 PM" width="1440" src="https://user-images.githubusercontent.com/94288784/199223997-23865e21-6ccc-4c39-9c58-e09098659369.png">

Hello ,
A few minutes ago i was trying Green Api send send message and i notices that regular text messages doesn’t takes time to sent but Attachment messages like Images,Videos, file takes time to send. Even while calling text message api it takes less time(1 sec) compare to calling file/Image/Video message (6-7 secs). I request developer team to process Image/Video/ files sending fast

**Comment by Slikman1** [comment]
Hello,  [adidesai9009](https://github.com/adidesai9009)! We will check the case and solve it at the near release.

**Comment by adidesai9009** [comment]
Its been 20 days that this issue is raised by till now there is now solution for it. After sending image via url it take 5-6 sec to receive image to receiver . Its is a big issue regarding resource usage. I request developer to look into it quickly .

**Comment by Smol2022** [comment]
Hello, at the moment, a whole file is uploaded every time you send it. The developers have fixed the file sending mechanism, it is currently being tested, and it will be implemented in the next release. Now we recommend reducing the size of the file being sent 21.11.2022, 11:05, "Aditya Desai" ***@***.***>: Its been 20 days that this issue is raised by till now there is now solution for it. After sending image via url it take 5-6 sec to receive image to receiver . Its is a big issue regarding resource usage. I request developer to look into it quickly .—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>  -- С уважением, Смольянова Елена.Yours faithfully, Smolianova Elena.Компания: "GREEN API"e-mail: ***@***.***: https://green-api.com/tel.: +79205048466https://wa.me/79205048466
